/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ToggleMetaYamlPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/utils/index.ts
var hideMetaClassName = "toggle-meta-yaml--hide";
function isHideMetaYaml() {
  return document.body.classList.contains(hideMetaClassName);
}
function showMetaYaml() {
  document.body.classList.remove(hideMetaClassName);
}
function hideMetaYaml() {
  document.body.classList.add(hideMetaClassName);
}

// src/main.ts
var ToggleMetaYamlPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log(`load ToggleMetaYaml`);
    this.addCommand({
      id: "obsidian-toggle-meta-yaml-toggle",
      name: "toggle",
      editorCallback: () => {
        if (isHideMetaYaml()) {
          showMetaYaml();
        } else {
          hideMetaYaml();
        }
      }
    });
  }
  onunload() {
    showMetaYaml();
  }
};
